server:
    port: ${PORT:8081}

spring:
    application:
        name: ${API_NAME:product}

    profiles:
        active: ${API_ENV:development}

    jackson:
        property-naming-strategy: SNAKE_CASE

    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL9Dialect

    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5433/product?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: admin
        password: 123456

app-config:
    secrets:
        api-secret: ${TOKEN_SECRET:YXV0aC1hcGktc2VjcmV0LWRldi0xMjM0NTY=}
